name: trodden
description: "Explore the world around you, one step at a time."

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.14.0
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  fl_chart: ^0.68.0
  provider: ^6.1.5
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  flutter_local_notifications: ^18.0.1
  http: ^1.2.1
  google_sign_in: ^7.2.0
  vibration: ^2.0.1
  audioplayers: ^6.1.0
  location: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.8

  # Change App Package Name
  change_app_package_name: ^1.5.0
  rename_app: ^1.6.5

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.7

# Splash Screen Settings
flutter_native_splash:
  color: "#030303" # Arka plan rengi
  image: assets/logo/splash600.png # Splash görüntüsü
  android_12:
    image: assets/logo/splash1152.png # Android 12+ için splash görüntüsü
    color: "#030303" # Arka plan rengi

# App Icon Settings
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"
  adaptive_icon_background: "#030303"
  adaptive_icon_foreground: "assets/logo/logo_transparent.png"
  min_sdk_android: 21
  remove_alpha_ios: true


flutter:

  uses-material-design: true
  assets:
    - assets/sounds/